# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffddad6953b14ef754d955a411f1aca5f1ce8a4c9bb231d9d7b7adfa5e9a10fd65edc83b20e0188dd49b31354b399dc8c8019f1ba9dbbfd84af70553d6989915

test:
  secret_key_base: cef3142df558b9121d3ca4011be71086a1f7d1aca5de5f0ff94e6a96d9c1af8af21f2b4695e216384dd6ef4d3a62bf7de19ad0c4f10b15b752d1263e2dfa1e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
